"""
Registry of niche keywords associated with specific manufacturers.

Pipeline role:
Provides the 'keyword boost' layer for the matching engine. While semantic 
matching captures general themes, this file captures precise technical terms 
(e.g., specific model numbers, proprietary technologies) that guarantee 
a match with nearly 100% precision.

Key responsibilities:
- Mapping manufacturer names to lists of high-intent technical keywords.
- Defining global keyword pools used for classifying tender relevance.

Notes:
- This is a manually curated list and is the primary source of 'truth' for 
  the hybrid matching strategy.
"""
company_keywords = {
    "Korvus Technology": [
        "Physical Vapour Deposition",
        "PVD",
        "Thin Film Deposition",
        "Magnetron Sputtering",
        "Electron Beam Evaporation",
        "E-beam Evaporation",
        "Thermal Boat Evaporation",
        "Low Temperature Evaporation",
        "Organic Deposition",
        "Ion Milling",
        "Multi-layer coating",
        "Co-deposition",
        "Sub-monolayer deposition",
        "High Vacuum",
        "UHV",
        "Ultra High Vacuum",
        "DC Sputtering",
        "RF Sputtering",
        "HiPIMS",
        "Pulsed-DC Sputtering",
        "Soft magnetic property deposition",
        "HEX Series",
        "HEX MINI",
        "HEX-L",
        "HEX-XL",
        "HEX UHV",
        "FISSION",
        "ORCA",
        "TAU",
        "TES",
        "FISSION Magnetron Sputtering Source",
        "ORCA Low Temperature Evaporation Source",
        "TAU Electron Beam Evaporator",
        "TES Thermal Boat Evaporation Source",
        "Modular PVD System",
        "Benchtop PVD",
        "Thin film deposition unit",
        "PVD coating machine",
        "Vacuum chamber system",
        "Magnetron sputter coater",
        "Mini E-beam evaporator",
        "Organic thin film deposition system",
        "Glovebox integrated PVD",
        "Thermal evaporator for metals",
        "High vacuum deposition platform",
        "Modular deposition chamber",
        "Four pocket electron beam source",
        "Research scale PVD system",
        "Base-stand mounted PVD",
        "Rack-mounted deposition system",
        "Material Science",
        "Semiconductors",
        "Photovoltaics",
        "Optics",
        "Nanomaterials",
        "Sensor applications",
        "Metal halide perovskites",
        "CsPbBr3 deposition",
        "CsPbCl3 deposition",
        "Lithium-Ion Battery fabrication",
        "All-Solid-State Thin-Film Battery",
        "2D material devices",
        "Electron microscopy specimen coating",
        "FIB SEM sample preparation",
        "Optoelectronics",
        "Photonics",
        "E-beam",
        "Sputter coater",
        "Coating chamber",
        "Vacuum evaporator",
        "Metal deposition system",
        "Thermal source",
        "Crucible evaporator",
        "Sputter source",
        "Glovebox evaporator",
        "Thin film tool",
        "Vapor deposition",
        "Layer growth system",
        "Deposition source",
        "Substrate coating"
],

    "SALD" : [
        "spatial atomic layer deposition",
        "sALD",
        "spatial ALD",
        "atmospheric pressure ALD",
        "AP-SALD",
        "plasma enhanced spatial ALD",
        "PE-sALD",
        "continuous atomic layer deposition",
        "self-limiting surface reaction",
        "gas curtain separation technology",
        "atomic scale thickness control",
        "sequential gas-phase chemical process",
        "conformal thin film growth",
        "low-temperature deposition",
        "non-vacuum thin film coating",
        "SALD R&D System",
        "SALD R&D Tool",
        "SALD Glovebox Tool",
        "SALD High Volume Production System",
        "SALD HVM Solutions",
        "SALD Roll-to-Roll System",
        "SALD Sheet-to-Sheet System",
        "SALD R2R Platform",
        "SALD S2S Platform",
        "Patented SALD Deposition Head",
        "Integrated Plasma SALD Source",
        "thin film deposition unit",
        "atomic layer deposition coating system",
        "conformal coating equipment",
        "high throughput ALD reactor",
        "atmospheric deposition machine",
        "roll-to-roll coating line",
        "wafer scale passivation system",
        "moisture barrier deposition tool",
        "metal oxide coating system",
        "nanocoating fabrication equipment",
        "surface functionalization system",
        "large area thin film system",
        "encapsulation layer tool",
        "buffer layer deposition system",
        "charge transport layer system",
        "perovskite solar cell passivation",
        "silicon PERC surface passivation",
        "solid-state battery electrode coating",
        "flexible electronics encapsulation",
        "OLED moisture barrier",
        "thin film solid-state batteries",
        "permeation barrier coating",
        "high-k dielectric deposition",
        "transparent conductive oxide (TCO)",
        "electron transport layer (ETL)",
        "hole transport layer (HTL)",
        "aluminum oxide Al2O3 deposition",
        "tin oxide SnO2 coating",
        "nickel oxide NiO coating",
        "zinc oxide ZnO:Al (AZO)",
        "titanium dioxide TiO2 layer",
        "electrolyzer membrane coating",
        "2.5D substrate coating",
        "porous substrate infiltration",
        "vaccum-free ALD",
        "in-line deposition system",
        "spatial CVD",
        "precursor efficient coating",
        "high-speed nanocoating",
        "barrier layer system",
        "thin film encapsulation (TFE)",
        "atomic layer processing (ALP)",
        "web handling coating system",
        "slot-die alternative",
        "spatial CVD reactor",
        "gas-phase surface engineering",
        "maskless patterning deposition",
        "nanolayer stack system"
],

    "Teer Coating": [
        # --- Core Technologies & Processes ---
        "Closed Field Unbalanced Magnetron Sputtering",
        "CFUBMS",
        "Physical Vapor Deposition",
        "PVD",
        "Plasma Assisted Chemical Vapor Deposition",
        "PACVD",
        "Magnetron Sputter Ion Plating",
        "MSIP",
        "Reactive Sputtering",
        "Ion Plating",
        "DC Sputtering",
        "Pulsed DC Sputtering",
        "RF Sputtering",
        "HIPIMS",
        "High Power Impulse Magnetron Sputtering",
        "Plasma Cleaning",
        "Ion Etching",
        "Thin Film Deposition",
        "Surface Engineering",

        # --- Product Names / Series / Equipment ---
        "UDP Series",
        "UDP-450",
        "UDP-650",
        "UDP-850",
        "UDP-1000",
        "UDP-1200",
        "ST-200",
        "ST-300",
        "ST-500",
        "ST-2000",
        "Scratch Tester",
        "Automatic Scratch Tester",
        "Macro-Scratch Tester",
        "Micro-Scratch Tester",
        "Cluster Tool",
        "Large Scale Coating System",
        "Batch Coating System",
        "Magnetron Sputter Source",

        # --- Materials & Coating Types (Tender-Specific) ---
        "MoS2 Coatings",
        "Solid Lubricant Coatings",
        "Diamond-Like Carbon",
        "DLC",
        "MoST",
        "Graphit-iC",
        "Dymon-iC",
        "Keramos",
        "CrN Coatings",
        "Chromium Nitride",
        "TiN Coatings",
        "Titanium Nitride",
        "TiAlN",
        "AlTiN",
        "Zirconium Nitride",
        "ZrN",
        "Multilayer Coatings",
        "Nanocomposite Coatings",
        "Biocompatible Coatings",
        "Dry Film Lubricant",

        # --- Tender Language Variants & Equipment Phrases ---
        "PVD Coating Machine",
        "PVD Coating Unit",
        "Sputtering System",
        "Sputter Coater",
        "Thin Film Deposition Tool",
        "Vacuum Coating Equipment",
        "Adhesion Testing Machine",
        "Coating Adhesion Tester",
        "Material Characterization System",
        "Tribology Testing Equipment",
        "Hardness Testing System",
        "Surface Analysis Equipment",
        "Vapor Deposition Plant",
        "Industrial Coating System",

        # --- Industry / Use-case Terms ---
        "Tribology",
        "Wear Resistance",
        "Friction Reduction",
        "Low Friction Coating",
        "Solid Lubrication",
        "Bipolar Plates",
        "Fuel Cell Coatings",
        "Aerospace Coatings",
        "Medical Device Coatings",
        "Cutting Tool Coatings",
        "Engine Component Coatings",
        "Optical Coatings",
        "Corrosion Protection",
        "Anti-Galling",
        "Hydrophobic Coatings",

        # --- Related Synonyms / Hidden Recall Terms ---
        "Plasma Source",
        "Vacuum Chamber",
        "Substrate Rotation System",
        "Target Materials",
        "Planar Magnetron",
        "Cylindrical Magnetron",
        "Glow Discharge",
        "Workpiece Manipulator",
        "Load Lock System",
        "Film Thickness Measurement",
        "Coating Hardness",
        "Friction Coefficient",
        "Wear Rate Measurement"
],
    
    "Lumex": [
        "Zeeman background correction",
        "Zeeman Atomic Absorption Spectrometry",
        "ZAAS",
        "Atomic Absorption Spectrometry",
        "AAS",
        "Graphite furnace atomic absorption spectrometry",
        "GFAAS",
        "Cold Vapor Atomic Absorption Spectrometry",
        "CV-AAS",
        "CVAAS",
        "Capillary Electrophoresis",
        "CE",
        "High Performance Capillary Electrophoresis",
        "HPCE",
        "Capillary Zone Electrophoresis",
        "CZE",
        "Micellar Electrokinetic Chromatography",
        "MEKC",
        "Capillary Gel Electrophoresis",
        "CGE",
        "Capillary Isoelectric Focusing",
        "CIEF",
        "Polymerase Chain Reaction",
        "Real-time PCR",
        "qPCR",
        "Microchip-based PCR",
        "Fourier Transform Infrared Spectroscopy",
        "FTIR",
        "Near-Infrared Spectroscopy",
        "NIR",
        "FT-NIR",
        "Fluorimetry",
        "Fluorometry",
        "Chemiluminescence",
        "Phosphorescence",
        "Nephelometry",
        "Photometry",
        "Direct thermal decomposition",
        "Pyrolysis",
        "Mercury thermospeciation",
        "Amalgamation technique",
        "Gold trap pre-concentration",
        "RA-915M",
        "RA-915 Lab",
        "RA-915AM",
        "RA-915 AMNG",
        "Light-915M2",
        "Capel-205",
        "Capel-105M",
        "AriaDNA",
        "Fluorat-02",
        "Fluorat-02-4M",
        "Fluorat-02-5M",
        "MGA-1000",
        "MGA-915",
        "InfraLUM FT-12",
        "InfraLUM FT-08",
        "AE-2 Petroleum Hydrocarbon Analyzer",
        "AH-1 Total Hardness Analyzer",
        "CRAB Oil Slicks Detector",
        "BA-15 Benzene Analyzer",
        "PYRO-915+ attachment",
        "RP-91NG attachment",
        "TERMION thermoreactor",
        "Elforun software",
        "SpectraLUM/PRO",
        "Mercury analyzer",
        "Mercury vapor analyzer",
        "Portable mercury analyzer",
        "Bench-top mercury analyzer",
        "Continuous mercury monitoring system",
        "CEMS mercury",
        "Ambient air mercury monitor",
        "Mercury in natural gas analyzer",
        "Stack gas mercury monitor",
        "Total gaseous mercury monitor",
        "TGM analyzer",
        "Mercury in soil analyzer",
        "Mercury in water analyzer",
        "Mercury in fish analyzer",
        "Real-time DNA analyzer",
        "Thermal cycler",
        "Rapid PCR system",
        "Grain quality analyzer",
        "NIR grain analyzer",
        "Milk quality analyzer",
        "Dairy analyzer",
        "FT-NIR express analyzer",
        "Oil-in-water monitor",
        "Automated water hardness analyzer",
        "Benzene in air analyzer",
        "Hydrocarbon gas analyzer",
        "Online water quality analyzer",
        "Laboratory spectrometer",
        "Environmental monitoring",
        "Minamata Convention compliance",
        "US EPA Method 30B",
        "US EPA Method 7473",
        "ASTM D6350",
        "ISO 12846",
        "EN 15852",
        "Stack emission monitoring",
        "Flue gas analysis",
        "Food safety testing",
        "Grain moisture and protein analysis",
        "Clinical diagnostics",
        "Veterinary pathogen detection",
        "Forensic toxicology",
        "Petrochemical analysis",
        "Hydrocarbon processing",
        "Occupational health and safety",
        "Workplace air monitoring",
        "Demercurization control",
        "Geochemical exploration",
        "Water and wastewater treatment",
        "Hg analyzer",
        "Mercury detector",
        "Mercury sniffer",
        "DNA amplifier",
        "Nucleic acid analyzer",
        "Molecular diagnostic system",
        "Chemical oxygen demand analyzer",
        "COD analyzer",
        "Total petroleum hydrocarbons analyzer",
        "TPH analyzer",
        "Turbidity meter",
        "UV-Vis spectrophotometer",
        "Filter fluorometer",
        "Zeeman mercury spectrometer",
        "Microchip thermal cycler"
],
    "Staton":[
        "PVD",
        "Physical Vapor Deposition",
        "PECVD",
        "Plasma Enhanced Chemical Vapor Deposition",
        "Magnetron Sputtering",
        "Cathodic Arc Evaporation",
        "HIPIMS",
        "High-Power Impulse Magnetron Sputtering",
        "DC Sputtering",
        "fsARC",
        "Arc Source Technology",
        "Plasma Technology",
        "Nanotechnology",
        "Thin Film Deposition",
        "Surface Engineering",
        "Vacuum Coating Technology",

        # 2. Product Names / Series
        "OCTOARC Series",
        "OCTOMAG Series",
        "PD700-G2",
        "PVD Coating Machine",
        "PVD Coating Equipment",
        "Vacuum Coating Unit",
        "Industrial Coating System",

        # 3. Tender Language Variants
        "Thin film deposition unit",
        "Vacuum deposition system",
        "Sputter coater",
        "Hard coating deposition system",
        "Plasma processing equipment",
        "Vacuum chamber system",
        "Surface treatment plant",
        "Tool coating equipment",
        "Batch coating system",
        "Automated PVD system",
        "Reactive sputtering system",

        # 4. Industry / Use-case Terms
        "Cutting tool reconditioning",
        "Hard coatings for inserts",
        "Coin die coating",
        "Forming tool coating",
        "Injection mold coating",
        "Die casting mold coating",
        "Decorative PVD coatings",
        "Wear resistant coatings",
        "Biocompatible coatings",
        "Medical device coating",
        "Micro-tool coating",
        "Oil and gas component coating",
        "Nanostructured PVD coatings",
        "High ionization deposition",
        "Adhesion enhancement",

        # 5. Related Synonyms / Hidden Recall Terms
        "Sputtering source",
        "Arc cathode",
        "Target utilization",
        "Deposition rate control",
        "Coating thickness control",
        "Plasma source",
        "Vacuum metallurgy",
        "Ion plating",
        "Thin film applicator",
        "Vapor deposition hardware",
        "Substrate pretreatment",
        "Surface modification system"
],
    "spinflex":[
    "Physical Vapor Deposition",
    "PVD coating machine",
    "PECVD system",
    "Magnetron Sputtering",
    "Cathodic Arc Evaporation",
    "HiPIMS",
    "High Power Impulse Magnetron Sputtering",
    "OCTOARC",
    "OCTOMAG",
    "M250-G2",
    "M500-G2",
    "M700-G2",
    "M1000-G2",
    "Vacuum deposition system",
    "Thin film deposition equipment",
    "Hard coating system",
    "Wear-resistant coating",
    "Titanium Nitride coating",
    "TiN",
    "TiAlN",
    "Titanium Aluminum Nitride",
    "Chromium Nitride",
    "CrN",
    "TiCN",
    "Titanium Carbonitride",
    "AlTiCrN",
    "Nanocomposite coating",
    "Multilayer coating",
    "Tribological coating",
    "Surface engineering equipment",
    "Ion plating system",
    "Batch coater",
    "Industrial PVD plant",
    "Cutting tool coating",
    "Mold and die coating",
    "Biocompatible PVD coating",
    "Decorative PVD finish",
    "Anti-corrosion thin film",
    "Friction reduction coating",
    "Plasma cathode evaporation",
    "Reactive sputtering",
    "Vacuum metallizer",
    "Hardness testing equipment",
    "Adhesion testing",
    "Surface roughness modification",
    "Tool life enhancement",
    "High-speed machining coatings",
    "Die casting mold protection",
    "Injection molding coatings",
    "Turn-key coating solution"
],
    "Nordiko":[
    # 1. Core Technologies
    "Ion Beam Systems",
    "Physical Vapour Deposition",
    "PVD",
    "Plasma Enhanced Chemical Vapour Deposition",
    "PECVD",
    "Sputtering",
    "Thin film deposition",
    "Ion Beam Etch",
    "Ion Beam Milling",
    "Broad Ion Beam",
    "BIB",
    "Ion Beam Deposition",
    "IBD",
    "Nano technology",
    "Dry etching",
    "Wafer handling",
    "Cluster arrangement",
    "Physical Vapor Deposition",

    # 2. Product Names / Series
    "Mnem-iX",
    "Nordiko 7500",
    "Nordiko 3400",
    "Nordiko 3000",
    "Nordiko alpha 120",
    "Nordiko α120",
    "Nordiko N2000",
    "Nordiko 2000 Series",
    "Nordiko 2550 Series",
    "Nordiko 5000",
    "Nordiko 8000",
    "Nordiko 8550",
    "Nordiko 9000",
    "Nordiko 9550",
    "Nordiko N1500",
    "Nordiko N300",
    "Nordiko 8800",
    "N2000",
    "N5000",
    "N300",

    # 3. Tender Language Variants
    "Thin film deposition system",
    "Ion beam milling system",
    "Broad ion beam deposition system",
    "Sputtering system",
    "Sputter coater",
    "Laboratory scale sputtering system",
    "Batch load PVD system",
    "Configurable process module",
    "Wafer handling platform",
    "Pilot production deposition system",
    "RD&I sputtering tool",
    "Large area PECVD system",
    "Atmospheric loading PECVD",
    "Process module integration",
    "Cluster tool platform",

    # 4. Industry / Use-case Terms
    "Semiconductor manufacturing",
    "Silicon processing",
    "III-V compound semiconductors",
    "II-VI compound semiconductors",
    "Magnetic heads fabrication",
    "Magnetic sensors",
    "MEMS fabrication",
    "Photonics",
    "LED manufacturing",
    "Laser Diode fabrication",
    "LDs",
    "Surface Acoustic Wave devices",
    "SAW devices",
    "Microbolometers",
    "Nano-fabrication",
    "Cleanroom equipment",
    "Thin film metrology",

    # 5. Related Synonyms / Hidden Recall Terms
    "Ion milling machine",
    "Ion beam source",
    "Vacuum deposition system",
    "Thin film coater",
    "Magnetron sputtering",
    "Reactive sputtering",
    "Substrate processing",
    "Etching station",
    "Wafer processing equipment",
    "Physical vapor deposition unit",
    "Plasma deposition",
    "Ion beam etching tool",
    "Thin film growth system"
], 
    "Genicore":[
        # 1. Core Technologies & Processes
        "Spark Plasma Sintering",
        "SPS",
        "Field Assisted Sintering Technique",
        "FAST",
        "Pulsed Electric Current Sintering",
        "PECS",
        "Pulse Plasma Compaction",
        "PPC",
        "Physical Vapor Deposition",
        "PVD",
        "Sputtering",
        "Magnetron Sputtering",
        "Diffusion Coating",
        "Thin Film Deposition",
        "Vacuum Technology",
        "High Vacuum",
        "HV",
        "Ultra High Vacuum",
        "UHV",
        "Space Environment Simulation",
        "Thermal Vacuum Testing",
        "Powder Metallurgy",
        "Sintering Technology",

        # 2. Product Names / Series / Equipment Families
        "U-FAST",
        "U-FAST GC",
        "U-FAST MASS",
        "U-FAST Hybrid",
        "U-FAST Glovebox",
        "Sliding Rail Tube Furnace",
        "Custom High Temperature Furnace",
        "Turbo Pumping Stations",
        "Mass Flow Controllers",
        "MFC",
        "Mass Flow Meters",
        "Helium Leak Detectors",
        "Ion Pumps",
        "Scroll Pumps",
        "Turbomolecular Pumps",
        "Turbo Pumps",
        "Dry Mechanical Pumps",
        "Industrial Dry Pumps",
        "Mechanical Oil Pumps",
        "Vacuum Gauging",
        "Vacuum Valves",
        "Graphite Dies",
        "Foreline Traps",
        "Mist and Dust Filters",
        "Pumping and Instrumentation Carts",

        # 3. Tender Language Variants
        "Thermal Vacuum System",
        "TVC System",
        "Sputtering System",
        "Coating Machine",
        "Vacuum Chamber System",
        "Vacuum Furnace",
        "Tube Furnace",
        "Inert Atmosphere Glove Box",
        "Controlled Atmosphere Glovebox",
        "Leak Testing Equipment",
        "Gas Flow Measurement Device",
        "Vacuum Pumping Skid",
        "High Vacuum Pumping Unit",
        "Thin Film Unit",
        "Materials Research Furnace",
        "Laboratory Vacuum System",
        "Benchtop Sintering Unit",
        "Industrial Vacuum Pump Supply",
        "Plasma Sintering Press",

        # 4. Industry / Use-case / Technical Terms
        "Aerospace Simulation",
        "Satellite Component Testing",
        "Surface Engineering",
        "Corrosive Environment Coating",
        "Elevated Temperature Testing",
        "Nano-material Sintering",
        "Ceramic Sintering",
        "Refractory Metal Processing",
        "Material Characterization Equipment",
        "Semiconductor Vacuum Components",
        "Research Lab Instrumentation",
        "Cleanroom Vacuum Systems",
        "Cryogenic Vacuum",
        "Residual Gas Analysis",
        "Pressure Measurement Instrumentation",

        # 5. Related Synonyms / Hidden Recall Terms
        "Sputter Coater",
        "E-beam Evaporation",
        "Thermal Evaporator",
        "Dry Scroll Vacuum Pump",
        "Rotary Vane Pump",
        "Diffusion Pump",
        "Vacuum Fittings",
        "KF Flanges",
        "CF Flanges",
        "ISO Flanges",
        "Vacuum Feedthroughs",
        "Bellows Sealed Valves",
        "Pneumatic Vacuum Valves",
        "Capacitance Manometer",
        "Pirani Gauge",
        "Penning Gauge",
        "Cold Cathode Gauge",
        "Hot Cathode Gauge",
        "Mass Flow Valve",
        "SPS Die Assembly",
        "Compaction Press"
        ],
    
    "pginstruments":[
        "Inductively Coupled Plasma Optical Emission Spectrometry",
        "ICP-OES",
        "ICP-AES",
        "Inductively Coupled Plasma Mass Spectrometry",
        "ICP-MS",
        "Dual View ICP",
        "Axial and Radial View Spectrometer",
        "Atomic Absorption Spectrometry",
        "AAS",
        "Graphite Furnace AAS",
        "Flame Atomic Absorption",
        "UV-Visible Spectrophotometry",
        "UV-Vis Spectrophotometer",
        "Single Beam Spectrophotometer",
        "Double Beam Spectrophotometer",
        "Rotating Disk Electrode Optical Emission Spectrometry",
        "RDE-OES",
        "Atomic Fluorescence Spectrometry",
        "Flame Photometry",
        "Microwave Digestion System",
        "Fourier Transform Infrared Spectroscopy",
        "FTIR",
        "Gas Chromatography",
        "GC",
        "Nano-Volume Spectrophotometry",
        "Micro-volume UV-Vis",
        "pH measurement",
        "Conductivity measurement",
        "Dissolved Oxygen analysis",
        "Ion Selective Electrode",
        "Potentiometric Titration",
        "Dissolution Testing",
        "ICP5000DV",
        "ICP5100DV",
        "PGI-OIL RDE",
        "AA500C",
        "NV200 Nano Volume",
        "T65 Series",
        "T85 Plus",
        "T95 Plus",
        "PG-SPARK OES",
        "P101 pH Meter",
        "P102 Conductivity Meter",
        "2400 Series Benchtop Meters",
        "Solid State RF Generator",
        "CCD Detector Spectrometer",
        "CFR 21 Part 11 Compliant Software",
        "ASTM D6595",
        "ASTM D6728",
        "Wear Metals Analyzer",
        "Oil Analysis Spectrometer",
        "Lubricant Testing Equipment",
        "Engine Fuel Analysis",
        "Trace Element Analysis",
        "Elemental Analyzer",
        "Water Quality Analysis",
        "Environmental Monitoring Instruments",
        "DNA RNA Protein Quantification",
        "Nucleic Acid Analysis",
        "OD600 Measurement",
        "Kinetic Scanning",
        "Spectrum Scanning",
        "Variable Bandpass Spectrophotometer",
        "Fixed Bandpass Spectrophotometer",
        "Motorised 8-cell changer",
        "Xenon Flash Lamp",
        "Argon Consumption Optimization",
        "Nebuliser and Spray Chamber",
        "Demountable Torch",
        "Hydride Generation System",
        "Hydra-Mist Analysis",
        "Sample Mineralization",
        "Laboratory Water Purifier",
        "Ultra-pure Water System",
        "Benchtop Analytical Instruments",
        "Handheld Water Quality Testers",
        "Metal Alloy Analysis",
        "Brine and Matrix Analysis",
        "Organic Solvent Analysis",
        "Solid State Maintenance Free Generator"
],
    "sintechnology":[
    # Core Technologies & Scientific Processes
    "residual stress measurement",
    "hole-drilling method",
    "ASTM E837",
    "mechanical testing",
    "thermodynamic testing",
    "operational modal analysis",
    "OMA",
    "strain gauge testing",
    "vibration monitoring",
    "structural health monitoring",
    "SHM",
    "non-destructive testing",
    "NDT",
    "semi-destructive testing",
    "experimental stress analysis",
    "electronic speckle pattern interferometry",
    "ESPI",
    "data acquisition",
    "DAQ",
    "signal processing",

    # Product Names / Series / Equipment Families
    "RESTAN",
    "MTS3000",
    "RSM system",
    "automatic hole-drilling system",
    "drilling device for residual stress",
    "residual stress analyzer",
    "strain gauge rosette",
    "optical measurement system",
    "mechanical diagnostic equipment",
    "data analysis software",
    "customized measurement instrumentation",

    # Tender Language Variants
    "residual stress measurement system",
    "automatic drilling unit for stress analysis",
    "material characterization equipment",
    "vibration analysis and monitoring system",
    "strain gauge data acquisition unit",
    "precision drilling system for NDT",
    "portable residual stress tester",
    "structural diagnostic instrumentation",
    "industrial monitoring and diagnostic system",
    "mechanical component testing rig",
    "thermodynamic data logger",

    # Industry / Use-case Terms
    "aerospace component testing",
    "turbomachinery diagnostics",
    "gas turbine blade analysis",
    "cultural heritage diagnostics",
    "monument structural monitoring",
    "power plant maintenance testing",
    "automotive component stress profiling",
    "welding residual stress analysis",
    "shot peening verification",
    "surface treatment validation",
    "pipeline stress monitoring",

    # Related Synonyms / Hidden Recall Terms
    "blind hole method",
    "stress profiling",
    "sub-surface stress measurement",
    "micro-drilling system",
    "strain rosette measurement",
    "stress relief analysis",
    "mechanical integrity testing",
    "modal testing",
    "vibration signature analysis",
    "material fatigue testing",
    "borehole stress measurement"
],
    "parteqgmbh":[
    # 1. Core Technologies & Processes
    "Flame Spray Pyrolysis",
    "FSP",
    "Chemical Vapor Deposition",
    "CVD",
    "Spark Ablation",
    "Hot Wall Synthesis",
    "Aerosol Science",
    "Particle Technology",
    "Atomization",
    "Evaporation Condensation",
    "Nanoparticle Synthesis",
    "Powder Functionalization",
    "Surface Modification",
    "Gas-phase Synthesis",

    # 2. Product Names / Series / Equipment Families
    "NPS-20",
    "Flame Spray Pyrolysis Unit",
    "Bench-top Nanoparticle Synthesis System",
    "Metal Nanopowder Generator",
    "Spark Discharge Generator",
    "Aerosol Instrumentation",
    "Nanoparticle Measurement System",
    "Filter Test Systems",
    "Nanopowder Collection System",
    "Aerosol Sampling Module",

    # 3. Tender Language Variants (Procurement-Facing)
    "Turn-key nanoparticle production system",
    "Laboratory-scale aerosol generator",
    "Pilot-scale particle synthesis reactor",
    "Aerosol characterization equipment",
    "Particle size measurement instrumentation",
    "Fine dust characterization apparatus",
    "Dustiness testing system",
    "Filter media efficiency analyzer",
    "High-temperature hot wall reactor",
    "Aerosol dilution and discharge system",
    "Particle sampling and conditioning unit",
    "Nanomaterial synthesis benchtop unit",

    # 4. Industry / Use-case Terms
    "Aerosol transport research",
    "Virus aerosol study equipment",
    "Material science research instrumentation",
    "Nanopowder manufacturing",
    "Airborne particle monitoring",
    "Industrial dust characterization",
    "Filter element validation",
    "Catalyst synthesis equipment",
    "Battery material research",
    "Powder metallurgy synthesis",

    # 5. Related Synonyms / Hidden Recall Terms
    "Nanomaterial generator",
    "Aerosol generator",
    "Particle counter calibration systems",
    "CVD coating reactor",
    "Vapor phase synthesis",
    "Nanoparticle collection filter",
    "Particle deposition system",
    "Aerosol neutralizer",
    "Aerosol diluter",
    "Static discharge systems for aerosols"
], 
    "gnr":[
    # 1. Core Technologies
    "Optical Emission Spectroscopy",
    "OES",
    "X-Ray Diffraction",
    "XRD",
    "X-Ray Fluorescence",
    "XRF",
    "Atomic Emission Spectroscopy",
    "AES",
    "Spark Emission",
    "Arc-Spark Spectrometry",
    "Crystallography",
    "Diffractometry",
    "Spectrometry",
    "Tribology",
    "Metallography",
    "Surface Metrology",

    # 2. Product Names / Series
    "Optical Emission Spectrometer",
    "X-Ray Diffractometer",
    "XRF Analyzer",
    "Sample Preparation Machine",
    "Grinding Machine",
    "Lapping Machine",
    "Polishing Machine",
    "Oil Analysis Spectrometer",
    "RDE Spectrometer",
    "Rotating Disc Electrode",
    "Benchtop Spectrometer",
    "Laboratory Spectrometer",

    # 3. Tender Language Variants
    "Metal analysis spectrometer",
    "Material characterization system",
    "Crystalline material analyzer",
    "Surface preparation equipment",
    "Lubricant condition monitoring system",
    "Spectrometric analysis unit",
    "Quantitative powder diffraction system",
    "Qualitative crystalline analysis",
    "Solid material characterization",
    "Elemental analysis instrument",
    "Non-destructive material analyzer",
    "Metallurgical sample preparation unit",
    "Used oil analysis machine",

    # 4. Industry / Use-case Terms
    "Quality Control",
    "QC Lab",
    "Foundry analysis",
    "Steel plant instrumentation",
    "Non-destructive testing",
    "NDT",
    "Phase identification",
    "Residual stress analysis",
    "Wear metal analysis",
    "Additive analysis",
    "Contaminant monitoring",
    "Chemical & Petrochemical analysis",
    "Pharmaceutical material science",
    "Environmental monitoring equipment",
    "Clinical laboratory instrumentation",

    # 5. Related Synonyms / Hidden Recall Terms
    "Spark-OES",
    "Total Reflection X-ray Fluorescence",
    "TXRF",
    "Spectrographic analysis",
    "Condition-based maintenance",
    "CBM",
    "Elemental analyzer",
    "Phase quantification",
    "Retained austenite measurement",
    "Texture analysis",
    "Thin film characterization",
    "Oil wetted component monitoring",
    "Preventive maintenance diagnostic",
    "Melt analysis"
], 
    "adnanotech": [
        # Core Technologies
        "Ultrahigh Vacuum",
        "UHV",
        "Molecular Beam Epitaxy",
        "MBE",
        "Laser MBE",
        "E-Beam Evaporation",
        "Electron Beam Evaporation",
        "Magnetron Sputtering",
        "DC Magnetron Sputtering",
        "RF Magnetron Sputtering",
        "Pulsed Laser Deposition",
        "PLD",
        "Thermal Evaporation",
        "Ion Beam Sputtering Deposition",
        "IBSD",
        "IBD",
        "Reactive Ion Etching",
        "RIE",
        "Inductively Coupled Plasma RIE",
        "ICP-RIE",
        "Electron Cyclotron Resonance RIE",
        "ECR-RIE",
        "Ion Beam Etching",
        "IBE",
        "Dry Etching",
        "Josephson Junction fabrication",
        "Thin Film Deposition",
        "Physical Vapor Deposition",
        "PVD",

        # Product Names / Series
        "EBS series",
        "JEB series",
        "JEB-2",
        "JEB-3",
        "JEB-4",
        "JEB Cluster System",
        "Linear Transfer System",
        "Automatic Transfer Arm",
        "UHV Transfer Robot",
        "Laser Heater Manipulator",
        "Multi-source deposition tool",

        # Tender Language Variants
        "Thin film deposition unit",
        "Vacuum coating machine",
        "PVD coating system",
        "UHV deposition system",
        "Plasma etching system",
        "Ion milling system",
        "Multi-chamber cluster tool",
        "Load-lock chamber system",
        "Substrate heating system",
        "Laser substrate heater",
        "High-temperature manipulator",
        "Automatic wafer transfer system",
        "Oxygen-compatible heater",
        "Multi-target PLD system",
        "Josephson Junction evaporator",

        # Industry / Use-case Terms
        "Quantum computing deposition",
        "Semiconductor fabrication equipment",
        "High-k dielectric deposition",
        "III-V material growth",
        "II-VI material growth",
        "Metal oxide deposition",
        "Elemental semiconductor deposition",
        "Organic thin film deposition",
        "Josephson Junction devices",
        "8-inch substrate processing",
        "12-inch wafer handling",
        "Research grade UHV system",

        # Related Synonyms / Hidden Recall Terms
        "e-beam coater",
        "sputter coater",
        "electron beam gun",
        "ion source",
        "plasma coil",
        "RF sample bias",
        "microwave plasma",
        "electro magnet plasma",
        "resistance heater",
        "ozone-rich deposition",
        "vacuum robot",
        "sample manipulator",
        "HfO2",
        "ZrO2",
        "Al2O3",
        "Sc2O3",
        "epitaxial growth system"
    ],

    "agnitron": [
        # Core Technologies & Process Names
        "MOCVD",
        "Metal Organic Chemical Vapor Deposition",
        "MOVPE",
        "Metalorganic Vapor Phase Epitaxy",
        "OMCVD",
        "Organometallic Chemical Vapor Deposition",
        "Epitaxial Growth",
        "Epitaxy",
        "CVD",
        "Chemical Vapor Deposition",
        "SCADA",
        "In-situ Monitoring",
        "Multiwavelength Pyrometry",
        "Emissivity Corrected Pyrometry",
        "Thin Film Deposition",
        "Ultra-wide bandgap",
        "UWBG",
        "Wide bandgap",
        "WBG",

        # Product Names / Series / Internal Naming
        "Agilis",
        "Agilis Mini",
        "Agilis 100",
        "Agilis 500",
        "Agilis 700",
        "Agilis A Series",
        "GOX Series",
        "GOX 300",
        "Imperium-MOCVD",
        "AgniTemp",

        # Tender Language Variants
        "MOCVD Reactor",
        "Epitaxial Growth System",
        "Semiconductor Deposition Tool",
        "Thin Film Deposition Unit",
        "MOCVD Control Software",
        "MOCVD Automation System",
        "Legacy MOCVD Upgrade",
        "Wafer Surface Temperature Measurement System",
        "Non-contact Temperature Sensor",
        "III-V Compound Semiconductor System",
        "Gallium Oxide Growth System",
        "2D Material Deposition System",
        "MOCVD Retrofitting Kit",
        "Epitaxy Process Controller",

        # Industry / Use-case / Materials
        "Semiconductor R&D",
        "Power Electronics",
        "RF Device Fabrication",
        "Optoelectronics",
        "High Electron Mobility Transistors",
        "HEMT",
        "Transition Metal Dichalcogenides",
        "TMD",
        "ScAlN",
        "Scandium Aluminum Nitride",
        "Ga2O3",
        "Gallium Oxide",
        "beta-Ga2O3",
        "AlGaO",
        "GaN",
        "Gallium Nitride",
        "AlGaN",
        "AlN",
        "InGaN",
        "MgZnO",
        "ZnO",
        "Zinc Oxide",
        "III-IV compounds",
        "As/P alloys",
        "AlGaAs",
        "InGaAlP",
        "MoS2",
        "MoSe2",
        "WS2",
        "WSe",
        "2D BN",
        "Boron Nitride",
        "Phosphorene",
        "SiC",
        "Silicon Carbide",

        # Related Synonyms / Hidden Recall Terms
        "Susceptor Rotation Control",
        "Wafer Heater Controller",
        "Gas Manifold System",
        "Mass Flow Controller Interface",
        "Vapor Phase Epitaxy System",
        "Crystal Growth Equipment",
        "Emcore Upgrade",
        "Veeco MOCVD Support",
        "Thomas Swan System Service",
        "Aixtron Control Replacement",
        "Structured Material Inc",
        "SMI MOCVD",
        "Process Data Logging Software",
        "Thermal Monitoring UXnit"
    ]
}